/*
3474. Lexicographically Smallest Generated String
Solved
Hard
Topics
premium lock icon
Companies
Hint
You are given two strings, str1 and str2, of lengths n and m, respectively.

A string word of length n + m - 1 is defined to be generated by str1 and str2 if it satisfies the following conditions for each index 0 <= i <= n - 1:

If str1[i] == 'T', the substring of word with size m starting at index i is equal to str2, i.e., word[i..(i + m - 1)] == str2.
If str1[i] == 'F', the substring of word with size m starting at index i is not equal to str2, i.e., word[i..(i + m - 1)] != str2.
Return the lexicographically smallest possible string that can be generated by str1 and str2. If no string can be generated, return an empty string "".



Example 1:

Input: str1 = "TFTF", str2 = "ab"

Output: "ababa"

Explanation:

The table below represents the string "ababa"
Index	T/F	Substring of length m
0	'T'	"ab"
1	'F'	"ba"
2	'T'	"ab"
3	'F'	"ba"
The strings "ababa" and "ababb" can be generated by str1 and str2.

Return "ababa" since it is the lexicographically smaller string.

Example 2:

Input: str1 = "TFTF", str2 = "abc"

Output: ""

Explanation:

No string that satisfies the conditions can be generated.

Example 3:

Input: str1 = "F", str2 = "d"

Output: "a"



Constraints:

1 <= n == str1.length <= 104
1 <= m == str2.length <= 500
str1 consists only of 'T' or 'F'.
str2 consists only of lowercase English characters.
*/

class Solution
{
public:
    bool isSame(string &word, string &str2, int i, int m)
    {
        for (int j = 0; j < m; j++)
        {
            if (word[i] != str2[j])
                return false;
            i++;
        }
        return true;
    }
    string generateString(string str1, string str2)
    {
        int n = str1.length(), m = str2.length();
        int N = n + m - 1;
        string word(N, '$');
        vector<bool> canChange(N, false);
        for (int i = 0; i < n; i++)
        {
            if (str1[i] == 'T')
            {
                int i_ = i;
                for (int j = 0; j < m; j++)
                {
                    if (word[i_] != '$' && word[i_] != str2[j])
                        return "";
                    word[i_] = str2[j];
                    i_++;
                }
            }
        }

        for (int i = 0; i < N; i++)
        {
            if (word[i] == '$')
            {
                word[i] = 'a';
                canChange[i] = true;
            }
        }

        for (int i = 0; i < n; i++)
        {
            if (str1[i] == 'F')
            {
                if (isSame(word, str2, i, m))
                {
                    bool check = false;
                    for (int k = i + m - 1; k >= i; k--)
                    {
                        if (canChange[k])
                        {
                            word[k] = 'b';
                            check = true;
                            break;
                        }
                    }
                    if (!check)
                        return "";
                }
            }
        }
        return word;
    }
};